Filtering output plots for:
c_diff c_vibrioides d_vulg e_coli e_fae e_limo


Removing existing data
rm: cannot remove ‘/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/c_diff/plots//*.csv’: No such file or directory
Filtering plots for c_diff
Clustering broke. Skipping.
Clustering broke. Skipping.
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/scipy/stats/_morestats.py:3189: RuntimeWarning: invalid value encountered in scalar divide
  W = numer / denom
Finished filtering outputs for c_diff into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/c_diff/plots/
----------------------------------------------------

Removing existing data
Filtering plots for c_vibrioides
Finished filtering outputs for c_vibrioides into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/c_vibrioides/plots/
----------------------------------------------------

Removing existing data
Filtering plots for d_vulg
Finished filtering outputs for d_vulg into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/d_vulg/plots/
----------------------------------------------------

Removing existing data
Filtering plots for e_coli
Finished filtering outputs for e_coli into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_coli/plots/
----------------------------------------------------

Removing existing data
rm: cannot remove ‘/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_fae/plots//*.csv’: No such file or directory
Filtering plots for e_fae
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:520: RuntimeWarning: Mean of empty slice.
  avg = a.mean(axis, **keepdims_kw)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:121: RuntimeWarning: invalid value encountered in divide
  ret = um.true_divide(
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:375: RuntimeWarning: Degrees of freedom <= 0 for slice
  sd = np.cov(cov_nocand, rowvar=0)  # type: ignore
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: divide by zero encountered in divide
  c *= np.true_divide(1, fact)
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/lib/function_base.py:2748: RuntimeWarning: invalid value encountered in multiply
  c *= np.true_divide(1, fact)
Clustering broke. Skipping.
Clustering broke. Skipping.
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/fromnumeric.py:3504: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/users/PDS0325/sachitk26/.conda/envs/tart/lib/python3.11/site-packages/numpy/core/_methods.py:129: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
Finished filtering outputs for e_fae into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_fae/plots/
----------------------------------------------------

Removing existing data
rm: cannot remove ‘/users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_limo/plots//*.csv’: No such file or directory
Filtering plots for e_limo
srun: Job 26435260 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for job 26435260
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:179: RuntimeWarning: divide by zero encountered in scalar divide
  return self.find_absolute_coverage_delta(sumcov) / sumcov[self.left]
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:179: RuntimeWarning: divide by zero encountered in scalar divide
  return self.find_absolute_coverage_delta(sumcov) / sumcov[self.left]
/users/PDS0325/sachitk26/packages/tart/tart/utils/activity_inference.py:179: RuntimeWarning: divide by zero encountered in scalar divide
  return self.find_absolute_coverage_delta(sumcov) / sumcov[self.left]
Clustering broke. Skipping.
Clustering broke. Skipping.
Clustering broke. Skipping.
Clustering broke. Skipping.
Clustering broke. Skipping.
Finished filtering outputs for e_limo into /users/PDS0325/sachitk26/packages/tart/validation/alignment/outputs/e_limo/plots/
----------------------------------------------------

Done
